# vim: set ft=toml :


min_version = '2026.4.8'


[hooks]
postinstall = [{ task = 'hooks-install' }, 'pixi install --all']


[settings]
experimental = true
lockfile = true
lockfile_platforms = ['linux-arm64', 'linux-x64', 'macos-arm64']


[tasks.all]
alias = 'default'
run = [
  { task = 'dbt-deps' },
  { task = 'dbt-run' },
  { task = 'dbt-test' },
  { task = 'mf' },
]

[tasks.dbt-deps]
run = 'pixi run -- dbt deps'

[tasks.dbt-run]
depends = ['jafgen']
run = 'pixi run -- dbt run'

[tasks.dbt-test]
run = 'pixi run -- dbt test'

[tasks.hooks-install]
hide = true
run = [{ task = 'hooks-uninstall' }, 'hk install --mise']

[tasks.hooks-uninstall]
hide = true
run = 'hk uninstall'

[tasks.jafgen]
run = """\
if test "$(find -- jaffle-data -name '*.csv' -print0 | tr -cd -- '\\0' | wc -c)" -eq 0; then \
pixi run -- jafgen; fi"""

[tasks.lint]
run = 'hk fix --all'

[tasks.mf]
run = [{ task = 'mf-health-checks' }, { task = 'mf-validate-configs' }]

[tasks.mf-health-checks]
run = 'pixi run -- mf health-checks'

[tasks.mf-validate-configs]
run = 'pixi run -- mf validate-configs --show-all --verbose-issues'

[tasks.upgrade]
run = ['mise upgrade --local', 'mise lock', 'pixi update']


[tools]
hk = 'latest'
pixi = 'latest'
pkl = 'latest'
