# vim: set ft=yaml :
#
# https://docs.getdbt.com/docs/local/profiles.yml
# https://docs.getdbt.com/reference/dbt-jinja-functions/profiles-yml-context
# https://github.com/duckdb/dbt-duckdb#readme


jaffle_shop:
  target: 'local'
  outputs:
    local:
      path: 'jaffle_shop.duckdb'
      settings:
        threads: 2
      threads: 4
      type: 'duckdb'
