# vim: set ft=yaml :
#
# https://taskfile.dev


version: '3'

set: ['errexit', 'nounset', 'pipefail']

includes:

  # https://changit.bwh.harvard.edu/nhlmi/manselmi-toybox/tree/main/local/Users/nhlmi/.taskfile/include/uv
  uv:
    taskfile: '{{ env "TASKFILE_INCLUDE_ROOT_DIR" }}/uv'
    vars:
      PYTHON_MINOR_VERSION: '3.11'

tasks:

  generate-seed-data:
    deps: ['uv:venv']
    vars:
      JAFFLE_DATA_SUCCESS: '{{ "jaffle-data/.success" | shellQuote }}'
      JAFGEN: '{{ .VENV | shellQuote }}/bin/jafgen'
    cmds:
      - 'rm -f -- {{ .JAFFLE_DATA_SUCCESS }}'
      - '{{ .JAFGEN }}'
      - 'touch -- {{ .JAFFLE_DATA_SUCCESS }}'
    status:
      - 'test -f {{ .JAFFLE_DATA_SUCCESS }}'

  build:
    aliases: ['default']
    deps: ['generate-seed-data']
    vars:
      DBT: '{{ .VENV | shellQuote }}/bin/dbt'
    cmds:
      - '{{ .DBT }} deps'
      - '{{ .DBT }} seed'
      - '{{ .DBT }} run'
      - '{{ .DBT }} test'

  mf-validate:
    deps: ['uv:venv']
    vars:
      MF: '{{ .VENV | shellQuote }}/bin/mf'
    cmds:
      - '{{ .MF }} health-checks'
      - '{{ .MF }} validate-configs --show-all --verbose-issues'
