# vim: set ft=yaml :
#
# https://taskfile.dev


version: '3'

set: ['errexit', 'nounset', 'pipefail']

includes:
  uv:
    taskfile: "{{ if env \"TASKFILE_INCLUDES_ROOT_DIR\" }}\
                 {{ env \"TASKFILE_INCLUDES_ROOT_DIR\" }}\
               {{ else }}\
                 {{ fail \"The TASKFILE_INCLUDES_ROOT_DIR environment variable must point to a directory with these files: https://changit.bwh.harvard.edu/nhlmi/manselmi-toybox/tree/main/local/Users/nhlmi/.taskfiles\" }}\
               {{ end }}/uv"
    vars:
      PYTHON_MINOR_VERSION: '3.11'

tasks:

  build:
    aliases: ['default']
    deps: ['uv:venv']
    vars:
      DBT: '{{ .VENV | shellQuote }}/bin/dbt'
    cmds:
      - '{{ .DBT }} deps'
      - '{{ .DBT }} seed'
      - '{{ .DBT }} run'
      - '{{ .DBT }} test'

  mf-validate:
    deps: ['uv:venv']
    vars:
      MF: '{{ .VENV | shellQuote }}/bin/mf'
    cmds:
      - '{{ .MF }} health-checks'
      - '{{ .MF }} validate-configs --verbose-issues'
