# vim: set ft=yaml :
#
# https://taskfile.dev


version: '3'

set: ['errexit', 'nounset', 'pipefail']

includes:
  uv:
    taskfile: '{{ env "TASKFILE_INCLUDES_ROOT_DIR" }}/uv'
    vars:
      PYTHON_MINOR_VERSION: '3.11'

tasks:

  build:
    aliases: ['default']
    deps: ['uv:venv']
    cmds:
      - '{{ .VENV }}/bin/dbt deps'
      - '{{ .VENV }}/bin/dbt seed'
      - '{{ .VENV }}/bin/dbt run'
      - '{{ .VENV }}/bin/dbt test'
