version: '3'

tasks:

  venv:
    cmds:
      - 'rm -fr -- .venv'
      - 'python3.11 -m venv -- .venv'
      - '.venv/bin/python -m pip install --progress-bar=off --upgrade -- pip setuptools wheel'
      - '.venv/bin/python -m pip install --progress-bar=off --no-deps -r requirements.txt'
      - '.venv/bin/python -m pip check'
      - 'printf %s "Signature: 8a477f597d28d172789f06886806bc55" > .venv/CACHEDIR.TAG'
    sources:
      - 'requirements.txt'
    generates:
      - '.venv/CACHEDIR.TAG'

  build:
    deps: ['venv']
    cmds:
      - '.venv/bin/dbt deps'
      - '.venv/bin/dbt seed'
      - '.venv/bin/dbt run'
      - '.venv/bin/dbt test'
